apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask-app
  namespace: devops-tools  # Assurez-vous que le namespace correspond
  labels:
    app: python-flask-app
    app.kubernetes.io/instance: python-flask  # Label ajouté pour correspondre au desired manifest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-flask-app
  template:
    metadata:
      labels:
        app: python-flask-app
    spec:
      nodeSelector:
        kubernetes.io/hostname: node02  # Corrigé : placé au bon niveau
      containers:
      - name: python-flask-container
        image: beups/python_flask:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: python-flask-service
  namespace: devops-tools  # Namespace explicitement mentionné
spec:
  selector:
    app: python-flask-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 32004
  type: NodePort
